# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: hackfolio

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline
  - serverless-webpack
  # - serverless-plugin-optimize

package:
  individually: true

custom:
  webpackIncludeModules:
    packagePath: './package.json'
  serverless-offline:
    port: 3002
  # optimize:
  #   minify: false

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: get
          cors: true
  profile:
    handler: handler.profile
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: profile
          method: get
          cors: true
